import Link from "next/link";
import type { ReactNode } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import {
  AnalyzeEvidenceCard,
  DefenderChecklist,
  FakeAlertCard,
  FakeDashboardCard,
  FakeLogPanel,
  KeyTakeaways,
  LessonProgressBar,
  MiniQuiz,
  PortfolioPrompt,
  ReadinessCheck,
  ScenarioDecisionLab,
} from "@/components/high-school/HighSchoolComponents";

const trackPath = "/high-school/advanced";
const modulePath = `${trackPath}/digital-forensics-concepts`;
const previousLesson = `${modulePath}/memory-and-storage-evidence-concepts`;
const nextLesson = `${modulePath}/log-correlation-for-forensics`;

const objectives = [
  "Distinguish fictional browser activity, account activity, authentication evidence, session evidence, notification evidence, and synchronization evidence without teaching invasive inspection or credential access.",
  "Evaluate fictional account and browser records using source health, time type, session state, shared-device context, automation, synchronization, stale-state limits, and privacy boundaries.",
  "Separate account association from person-level attribution and distinguish a login, session, notification, browser event, or account change from proof of intent, compromise, or physical identity.",
  "Map bounded fictional forensic questions to the minimum browser and account evidence categories needed, while excluding unrelated private content, credentials, messages, and broad personal activity.",
  "Write fictional forensic findings that preserve supported observations, alternative explanations, Unknown states, attribution limits, privacy concerns, and source limitations.",
];

const vocabulary = [
  {
    term: "Authentication event",
    definition:
      "A fictional record indicating that an account authentication action or state change occurred, without automatically proving who physically initiated it.",
  },
  {
    term: "Session",
    definition:
      "A fictional period in which an account or browser context is represented as active, subject to state, timing, device, and source limitations.",
  },
  {
    term: "Session continuity",
    definition:
      "The fictional relationship between session start, continuation, renewal, timeout, reauthentication, and end state.",
  },
  {
    term: "Account event",
    definition:
      "A fictional record associated with account state, approval, login, logout, role, recovery, notification, or another identity-related action.",
  },
  {
    term: "Browser activity",
    definition:
      "A high-level fictional evidence category describing navigation, browser state, session context, or related activity without teaching extraction or access methods.",
  },
  {
    term: "Notification",
    definition:
      "A fictional message or event generated by a service to report an account action, approval, warning, or status change.",
  },
  {
    term: "Shared-device ambiguity",
    definition:
      "A fictional limitation where more than one approved person can use the same endpoint or browser environment.",
  },
  {
    term: "Stale session",
    definition:
      "A fictional session that may remain represented as active even when the original user is no longer physically present.",
  },
  {
    term: "Automation",
    definition:
      "A fictional system-driven action that may create browser, account, or session records without a person manually performing every step.",
  },
  {
    term: "Synchronization",
    definition:
      "A fictional process that may reflect browser or account state across devices or services, complicating origin and attribution.",
  },
  {
    term: "Attribution limit",
    definition:
      "A documented boundary explaining what the fictional evidence does not establish about the physical person, intent, or cause.",
  },
  {
    term: "Account recovery state",
    definition:
      "A fictional account lifecycle state associated with approved recovery or restoration activity, without exposing secrets or recovery procedures.",
  },
];

const evidenceCategories = [
  {
    category: "Authentication records",
    maySupport:
      "That a fictional account authentication event or state change was recorded at a defined time.",
    doesNotProve:
      "Who physically initiated the action, why it occurred, or whether the account was compromised.",
    privacy:
      "Use only fictional account reference, time, result, context, and owner-approved fields; never include real credentials or secrets.",
    owner:
      "Fictional identity owner",
  },
  {
    category: "Session records",
    maySupport:
      "That a fictional account or browser session existed, changed state, renewed, timed out, or ended.",
    doesNotProve:
      "That one person continuously controlled the session or manually performed every action.",
    privacy:
      "Avoid unrelated session content, broad browsing history, or private communications.",
    owner:
      "Fictional identity and application owners",
  },
  {
    category: "Browser navigation summaries",
    maySupport:
      "That the fictional browser context referenced one or more approved destinations or application pages.",
    doesNotProve:
      "Why a page appeared, who physically navigated to it, what all page content contained, or whether the activity was harmful.",
    privacy:
      "Use only fully invented destinations and minimum high-level navigation summaries.",
    owner:
      "Fictional browser or application evidence owner",
  },
  {
    category: "Account state changes",
    maySupport:
      "That a fictional account role, status, approval, recovery state, or policy state changed.",
    doesNotProve:
      "That the change was unauthorized or caused later activity.",
    privacy:
      "Use fictional state labels and do not include real security questions, recovery secrets, or internal identity configuration.",
    owner:
      "Fictional identity governance owner",
  },
  {
    category: "Notifications",
    maySupport:
      "That a fictional service generated a warning, approval notice, state change, or account-related message.",
    doesNotProve:
      "That the recipient saw the message, acted on it, or that the notification accurately describes complete account activity.",
    privacy:
      "Use invented notification summaries rather than private message content.",
    owner:
      "Fictional service or identity owner",
  },
  {
    category: "Synchronization records",
    maySupport:
      "That fictional browser or account state was reflected across multiple devices or services.",
    doesNotProve:
      "Which location originated the state or which person initiated it.",
    privacy:
      "Use high-level synchronization relationships only, without real device or account details.",
    owner:
      "Fictional application or identity owner",
  },
  {
    category: "Shared-device context",
    maySupport:
      "That a fictional browser or account event occurred on a device approved for multiple users.",
    doesNotProve:
      "Which approved person physically controlled the device at the time.",
    privacy:
      "Use fictional role groups rather than real people or personal device details.",
    owner:
      "Fictional endpoint owner",
  },
  {
    category: "Account recovery or support context",
    maySupport:
      "That a fictional account was in an approved recovery, support, or restoration workflow.",
    doesNotProve:
      "That every later event was authorized, or that recovery itself caused the activity.",
    privacy:
      "Never include real recovery secrets, security answers, backup codes, credentials, or bypass details.",
    owner:
      "Fictional identity support owner",
  },
];

const evidenceMatrix = [
  {
    id: "BA-01",
    category: "Authentication event",
    observation:
      "A fictional authentication record shows Account A successfully entered an approved service session at 14:01.",
    supports:
      "Account A was represented as successfully authenticated at that time.",
    limits:
      "The record does not independently identify the physical person or prove the session remained continuously controlled by one person.",
    sourceHealth: "Healthy",
    confidence: "High",
    nextQuestion:
      "What session, device, approval, and shared-use context applies?",
  },
  {
    id: "BA-02",
    category: "Session record",
    observation:
      "The fictional session remained active until 14:19 without a second authentication event.",
    supports:
      "The service represented one continuing session during that interval.",
    limits:
      "Session continuity does not prove continuous physical presence or manual activity.",
    sourceHealth: "Conditional",
    confidence: "Moderate",
    nextQuestion:
      "Could session persistence, automation, or shared-device use explain later events?",
  },
  {
    id: "BA-03",
    category: "Browser navigation summary",
    observation:
      "The fictional browser summary references the Support Console and Workflow Review page between 14:03 and 14:06.",
    supports:
      "Those pages were represented in the browser context during the approved window.",
    limits:
      "The summary does not prove who navigated, what every page contained, or whether the navigation caused a workflow change.",
    sourceHealth: "Conditional",
    confidence: "Moderate",
    nextQuestion:
      "Which supplied application and workflow records connect the browser context to the bounded forensic question?",
  },
  {
    id: "BA-04",
    category: "Notification event",
    observation:
      "A fictional service generated a role-change notification for Account A at 13:46.",
    supports:
      "The service produced a notification associated with the account state change.",
    limits:
      "The record does not prove the recipient saw, understood, or acted on the notification.",
    sourceHealth: "Healthy",
    confidence: "High",
    nextQuestion:
      "What approved role state was effective and when?",
  },
  {
    id: "BA-05",
    category: "Synchronization state",
    observation:
      "A fictional browser state associated with the Support Console appeared on two approved endpoints after synchronization.",
    supports:
      "The browser state was reflected in both device contexts.",
    limits:
      "The supplied evidence does not independently establish which endpoint originated the state.",
    sourceHealth: "Healthy",
    confidence: "Moderate",
    nextQuestion:
      "What synchronization direction, delay, and shared-device context applies?",
  },
  {
    id: "BA-06",
    category: "Account recovery context",
    observation:
      "A fictional support record shows Account A completed an approved recovery workflow before the review window.",
    supports:
      "The account was in an authorized recovery lifecycle before later activity.",
    limits:
      "The recovery state does not prove every later event was authorized or that recovery caused the later activity.",
    sourceHealth: "Healthy",
    confidence: "High",
    nextQuestion:
      "Which later account and session events require independent evaluation?",
  },
];

const attributionLadder = [
  {
    level: "Account association",
    example:
      "The fictional event is associated with Account A.",
    limit:
      "Does not identify the physical person.",
  },
  {
    level: "Session association",
    example:
      "The fictional event occurred during Session S tied to Account A.",
    limit:
      "Does not prove continuous person control or manual action.",
  },
  {
    level: "Device association",
    example:
      "The fictional browser state appeared on shared Endpoint D-17.",
    limit:
      "Does not identify which approved user controlled the endpoint.",
  },
  {
    level: "Browser-context association",
    example:
      "The fictional browser summary references the Support Console.",
    limit:
      "Does not prove the user's intent, attention, or every page interaction.",
  },
  {
    level: "Person attribution",
    example:
      "A specific fictional person physically performed the activity.",
    limit:
      "Requires stronger evidence and may remain Unknown.",
  },
  {
    level: "Intent",
    example:
      "The activity was deliberate, harmful, deceptive, or unauthorized.",
    limit:
      "Requires context beyond account, browser, notification, or session evidence alone.",
  },
];

const ambiguityPatterns = [
  {
    pattern: "Shared device",
    explanation:
      "The fictional endpoint is approved for multiple users.",
    risk:
      "Browser or account evidence may be misreported as proof of one person's physical activity.",
    control:
      "Report account/device association and preserve person attribution as Unknown unless stronger evidence exists.",
  },
  {
    pattern: "Stale session",
    explanation:
      "A fictional session remains active after the original user may have left the device.",
    risk:
      "Later activity may be attributed to the person who originally authenticated.",
    control:
      "Separate session identity from physical-presence assumptions.",
  },
  {
    pattern: "Automation",
    explanation:
      "A fictional service or browser workflow can generate background events automatically.",
    risk:
      "Automated activity may be described as a person's manual navigation or account action.",
    control:
      "Ask whether the supplied evidence distinguishes manual and automated activity.",
  },
  {
    pattern: "Synchronization",
    explanation:
      "A fictional browser or account state may appear on another approved device after synchronization.",
    risk:
      "Presence may be mistaken for local origin.",
    control:
      "Separate reflected state from origin and preserve synchronization delay.",
  },
  {
    pattern: "Notification without acknowledgement",
    explanation:
      "A fictional notification was generated, but there is no evidence the recipient saw it.",
    risk:
      "Notification generation may be described as user awareness or consent.",
    control:
      "State only that the service generated the notification unless acknowledgement is separately supported.",
  },
  {
    pattern: "Recovery context",
    explanation:
      "A fictional account completed an approved recovery workflow before later activity.",
    risk:
      "Recovery may be treated as proof that all later activity was approved or safe.",
    control:
      "Evaluate later events independently and use recovery only as context.",
  },
];

const privacyQuestions = [
  {
    question:
      "Does the fictional forensic question require broad browsing history?",
    answer:
      "Usually no. Use only the minimum invented browser context necessary for the approved question.",
  },
  {
    question:
      "Does account investigation require credentials or secrets?",
    answer:
      "No. CyberShield never uses real or fictional credential values, recovery secrets, backup codes, or security answers.",
  },
  {
    question:
      "Should private message content be reviewed because it exists in a browser session?",
    answer:
      "No. Unrelated private communications remain excluded unless an entirely separate qualified owner and purpose explicitly governs the scenario.",
  },
  {
    question:
      "Should every device synchronized to the account enter scope?",
    answer:
      "No. Synchronization does not automatically create relevance or authority.",
  },
  {
    question:
      "Can browser evidence be shown in a public portfolio?",
    answer:
      "Only as fully invented, public-safe summaries with no real URLs, accounts, screenshots, messages, or internal details.",
  },
  {
    question:
      "What happens when the next evidence step would expose unrelated personal activity?",
    answer:
      "Stop, minimize, and escalate to the appropriate fictional privacy or governance owner.",
  },
];

const reportingPatterns = [
  {
    weak:
      "Person A logged in and performed the action.",
    stronger:
      "The fictional authentication and session records associate Account A with the service during the review window; the current evidence does not independently establish the physical person who performed each action.",
  },
  {
    weak:
      "The browser history proves the user visited the page intentionally.",
    stronger:
      "The supplied fictional browser summary references the page during the review window; intent, attention, and physical-user attribution are not established by the summary alone.",
  },
  {
    weak:
      "The notification proves the user knew about the role change.",
    stronger:
      "The fictional service generated a role-change notification; the current evidence does not establish that the recipient saw or acknowledged it.",
  },
  {
    weak:
      "The synchronized browser state proves D-17 originated the activity.",
    stronger:
      "The fictional browser state was reflected on D-17 after synchronization; origin remains unresolved.",
  },
  {
    weak:
      "The recovery workflow made the account safe.",
    stronger:
      "The fictional account completed an approved recovery workflow before the review window; later account and session activity still require independent evaluation.",
  },
  {
    weak:
      "The session proves continuous user presence.",
    stronger:
      "The fictional session remained active through the interval; the evidence does not independently prove continuous physical presence or manual activity.",
  },
];

const questionToEvidence = [
  {
    question:
      "Was fictional Account A successfully authenticated to Service S at 14:01?",
    useful:
      "Authentication record, source health, account reference, event time, result.",
    exclude:
      "Unrelated browser history, private messages, broad account profile, recovery secrets.",
    limit:
      "Authentication success does not identify the physical person.",
  },
  {
    question:
      "Did the fictional session remain active during the workflow event?",
    useful:
      "Session state, start/end, renewal or timeout state, source health, time context.",
    exclude:
      "Unrelated account activity outside the approved window.",
    limit:
      "Active session does not prove continuous user presence.",
  },
  {
    question:
      "Was the fictional Support Console represented in the browser context?",
    useful:
      "Browser navigation summary, session association, source health, time range.",
    exclude:
      "Full browsing history or unrelated websites.",
    limit:
      "Browser representation does not prove intent or manual navigation.",
  },
  {
    question:
      "Was a fictional role-change notification generated?",
    useful:
      "Notification event, account state change, event time, recipient account reference.",
    exclude:
      "Private message content or unrelated notifications.",
    limit:
      "Generated does not mean seen or acknowledged.",
  },
];

const sessionStates = [
  {
    state: "Started",
    meaning:
      "The fictional service recorded session establishment.",
    limit:
      "Does not prove the same person controlled the session later.",
  },
  {
    state: "Active",
    meaning:
      "The fictional session remained represented as usable.",
    limit:
      "Does not prove continuous physical presence or manual activity.",
  },
  {
    state: "Renewed",
    meaning:
      "The fictional session lifecycle extended under service rules.",
    limit:
      "Renewal may be automated and does not automatically imply a fresh person-level authentication.",
  },
  {
    state: "Idle",
    meaning:
      "The fictional session showed limited or no recorded interaction for a period.",
    limit:
      "Idle does not prove nobody had access or that no background activity occurred.",
  },
  {
    state: "Timed out",
    meaning:
      "The fictional service ended the session after its configured lifecycle condition.",
    limit:
      "Timeout does not explain all prior activity.",
  },
  {
    state: "Ended",
    meaning:
      "The fictional session was recorded as closed or invalid.",
    limit:
      "Does not prove all synchronized or downstream state disappeared immediately.",
  },
];

function SectionCard({
  eyebrow,
  title,
  children,
}: {
  eyebrow: string;
  title: string;
  children: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-slate-800 bg-slate-900/70 p-6 shadow-2xl shadow-cyan-950/20">
      <p className="text-xs font-semibold uppercase tracking-[0.25em] text-cyan-300">
        {eyebrow}
      </p>
      <h2 className="mt-2 text-2xl font-bold text-white">{title}</h2>
      <div className="mt-4 text-slate-300">{children}</div>
    </section>
  );
}

function Navigation() {
  return (
    <div className="flex flex-wrap gap-3">
      <Link
        href={previousLesson}
        className="rounded-xl border border-slate-700 px-5 py-3 font-bold text-slate-200 transition hover:border-cyan-400 hover:text-cyan-200"
      >
        Previous Lesson
      </Link>
      <Link
        href={modulePath}
        className="rounded-xl border border-slate-700 px-5 py-3 font-bold text-slate-200 transition hover:border-purple-400 hover:text-purple-200"
      >
        Module A8
      </Link>
      <Link
        href={nextLesson}
        className="rounded-xl bg-cyan-400 px-5 py-3 font-bold text-slate-950 transition hover:bg-cyan-300"
      >
        Next Lesson
      </Link>
    </div>
  );
}

export default function BrowserAndAccountActivityConceptsPage() {
  return (
    <main className="min-h-screen bg-slate-950 text-slate-100">
      <Navbar />

      <section className="border-b border-slate-800 bg-[radial-gradient(circle_at_top_left,_rgba(34,211,238,0.18),_transparent_35%),radial-gradient(circle_at_top_right,_rgba(168,85,247,0.14),_transparent_30%),linear-gradient(135deg,_#020617_0%,_#0f172a_55%,_#111827_100%)]">
        <div className="mx-auto max-w-6xl px-6 py-16">
          <div className="mb-8 flex flex-wrap gap-3 text-sm font-bold uppercase tracking-[0.2em]">
            <span className="rounded-full border border-cyan-400/40 bg-cyan-400/10 px-4 py-2 text-cyan-200">
              High School Advanced
            </span>
            <span className="rounded-full border border-purple-400/40 bg-purple-400/10 px-4 py-2 text-purple-200">
              Module A8
            </span>
            <span className="rounded-full border border-slate-700 bg-slate-900/70 px-4 py-2 text-slate-200">
              Lesson A8.6
            </span>
            <span className="rounded-full border border-emerald-400/40 bg-emerald-400/10 px-4 py-2 text-emerald-200">
              Browser and Identity Evidence
            </span>
          </div>

          <h1 className="max-w-5xl text-4xl font-black tracking-tight text-white md:text-6xl">
            A8.6 Browser and Account Activity Concepts
          </h1>

          <p className="mt-6 max-w-4xl text-lg leading-8 text-slate-300">
            Learn how professional fictional investigators reason about
            authentication, sessions, browser context, notifications, account
            state changes, synchronization, shared devices, stale sessions, and
            recovery context while protecting privacy and avoiding unsupported
            person-level attribution.
          </p>

          <div className="mt-8">
            <Navigation />
          </div>
        </div>
      </section>

      <div className="mx-auto grid max-w-6xl gap-8 px-6 py-10">
        <LessonProgressBar
          track="High School Advanced"
          moduleTitle="A8: Digital Forensics Concepts"
          lessonTitle="Browser and Account Activity Concepts"
          lessonNumber={6}
          totalLessons={10}
        />

        <ReadinessCheck
          title="Before You Start"
          items={[
            "I will use only invented browser records, account events, session states, notifications, devices, services, and timelines supplied in the lesson.",
            "I will not access real accounts, inspect real browsing activity, obtain credentials, review private messages, recover secrets, or bypass account protections.",
            "I will treat authentication, session, browser, notification, and account evidence as conceptual categories rather than access instructions.",
            "I will separate account association from physical-person attribution and preserve shared-device, stale-session, automation, and synchronization limits.",
            "I will use minimization and keep unrelated personal activity outside the fictional forensic purpose.",
            "I will keep every CyberShield example fully fictional, non-invasive, defensive, privacy-safe, and public-safe.",
          ]}
        />

        <SectionCard
          eyebrow="Professional Hook"
          title="A Successful Login Does Not Tell You Who Was at the Keyboard"
        >
          <p className="leading-8">
            A fictional authentication record shows Account A successfully
            entered Service S at 14:01. The session remained active until 14:19,
            and the browser context later referenced the Support Console. A
            rushed report says, “Person A logged in and used the Support
            Console.” But D-17 is a shared workstation, session continuity does
            not prove continuous physical presence, and some browser activity
            may be generated automatically.
          </p>

          <p className="mt-4 leading-8">
            A professional report preserves what each layer supports. The
            authentication record supports account-level authentication. The
            session record supports session continuity. The browser summary
            supports browser-context association. Person-level attribution
            remains a separate conclusion that may stay Unknown.
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            <div className="rounded-2xl border border-red-400/30 bg-red-400/10 p-5 text-red-50">
              <p className="text-xs font-black uppercase tracking-[0.18em] text-red-200">
                Weak conclusion
              </p>
              <p className="mt-2 leading-7">
                “Person A logged in and performed every action in the session.”
              </p>
            </div>

            <div className="rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-5 text-emerald-50">
              <p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-200">
                Professional conclusion
              </p>
              <p className="mt-2 leading-7">
                “The supplied fictional evidence associates Account A with an
                authenticated session and browser context during the review
                window; continuous physical-person control and manual action are
                not independently established.”
              </p>
            </div>
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Learning Objectives"
          title="Five Objectives for A8.6"
        >
          <div className="grid gap-4 md:grid-cols-2">
            {objectives.map((objective, index) => (
              <div
                key={objective}
                className="rounded-2xl border border-blue-400/25 bg-blue-400/10 p-5 text-blue-50"
              >
                <p className="text-xs font-black uppercase tracking-[0.16em] text-blue-200">
                  Objective {index + 1}
                </p>
                <p className="mt-3 text-sm font-semibold leading-7">
                  {objective}
                </p>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Why It Matters"
          title="Identity Evidence Is Powerful Because It Looks Personal"
        >
          <p className="leading-8">
            Account and browser evidence often includes human-readable account
            references, session labels, page names, notifications, and approval
            states. That can make the evidence feel more personal than it really
            is. An account identifier is not the same thing as a physical
            person, and a browser page reference is not the same thing as
            intent.
          </p>

          <p className="mt-4 leading-8">
            Professional forensic reasoning keeps identity layers separate.
            Account evidence describes the account. Session evidence describes
            the session. Browser evidence describes browser context.
            Notification evidence describes a generated message or event.
            Person attribution requires stronger support and may remain
            unresolved.
          </p>

          <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {[
              [
                "Identity discipline",
                "Keep fictional account objects separate from physical people.",
              ],
              [
                "Session discipline",
                "Do not treat a continuing session as proof of continuous manual control.",
              ],
              [
                "Browser discipline",
                "Do not treat a page reference as proof of intent or full user behavior.",
              ],
              [
                "Privacy discipline",
                "Use only the minimum fictional account and browser context necessary.",
              ],
            ].map(([title, detail]) => (
              <div
                key={title}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="font-black text-cyan-100">{title}</h3>
                <p className="mt-3 text-sm leading-6 text-slate-300">
                  {detail}
                </p>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Core Framework"
          title="Eight Browser and Account Evidence Categories"
        >
          <div className="grid gap-5">
            {evidenceCategories.map((item, index) => (
              <article
                key={item.category}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <div className="flex items-start gap-4">
                  <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-cyan-400 font-black text-slate-950">
                    {index + 1}
                  </span>
                  <div>
                    <h3 className="text-xl font-black text-white">
                      {item.category}
                    </h3>
                    <p className="mt-2 text-sm leading-7 text-slate-300">
                      Owner: {item.owner}
                    </p>
                  </div>
                </div>

                <div className="mt-4 grid gap-4 md:grid-cols-3">
                  <div className="rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-emerald-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-200">
                      May support
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.maySupport}</p>
                  </div>
                  <div className="rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-yellow-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-yellow-200">
                      Does not prove
                    </p>
                    <p className="mt-2 text-sm leading-6">
                      {item.doesNotProve}
                    </p>
                  </div>
                  <div className="rounded-xl border border-purple-400/25 bg-purple-400/10 p-4 text-purple-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-purple-200">
                      Privacy boundary
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.privacy}</p>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Vocabulary"
          title="Professional Terms for Browser and Account Evidence"
        >
          <div className="grid gap-4 md:grid-cols-2">
            {vocabulary.map((item) => (
              <div
                key={item.term}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="font-black text-cyan-100">{item.term}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-300">
                  {item.definition}
                </p>
              </div>
            ))}
          </div>
        </SectionCard>

        <FakeDashboardCard
          title="Fictional Browser and Account Evidence Dashboard"
          subtitle="Northbridge A8 exercise — invented evidence only"
          metrics={[
            {
              label: "Evidence items",
              value: "6",
              note: "Authentication, session, browser, notification, synchronization, recovery",
            },
            {
              label: "Shared endpoints",
              value: "1",
              note: "Physical-user attribution remains Unknown",
            },
            {
              label: "Conditional records",
              value: "2",
              note: "Session continuity and browser summary",
            },
            {
              label: "Open alternatives",
              value: "4",
              note: "Shared use, stale session, automation, synchronization",
            },
          ]}
        />

        <SectionCard
          eyebrow="Fictional Evidence Matrix"
          title="What Browser and Account Records Actually Support"
        >
          <div className="grid gap-5">
            {evidenceMatrix.map((item) => (
              <article
                key={item.id}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <div className="flex flex-wrap items-center gap-3">
                  <span className="rounded-full border border-cyan-400/30 bg-cyan-400/10 px-3 py-1 font-mono text-xs font-black text-cyan-200">
                    {item.id}
                  </span>
                  <h3 className="font-black text-white">{item.category}</h3>
                  <span className="rounded-full border border-yellow-400/30 bg-yellow-400/10 px-3 py-1 text-xs font-bold text-yellow-100">
                    {item.sourceHealth}
                  </span>
                  <span className="rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-100">
                    {item.confidence}
                  </span>
                </div>

                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  {[
                    ["Observation", item.observation],
                    ["Supports", item.supports],
                    ["Limitation", item.limits],
                    ["Next bounded question", item.nextQuestion],
                  ].map(([label, detail]) => (
                    <div
                      key={`${item.id}-${label}`}
                      className="rounded-xl border border-slate-700 bg-slate-900 p-4"
                    >
                      <p className="text-xs font-black uppercase tracking-[0.16em] text-purple-200">
                        {label}
                      </p>
                      <p className="mt-2 text-sm leading-6 text-slate-300">
                        {detail}
                      </p>
                    </div>
                  ))}
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <FakeAlertCard
          title="Fictional Account Attribution Warning"
          severity="High"
          time="Fictional review window"
          source="Supplied fictional evidence"
          details="Account A is associated with the session, but D-17 is shared and the supplied evidence does not identify the physical person."
          recommendation={["Authentication event: Account A successful at 14:01",
            "Session state: active until 14:19",
            "Endpoint context: shared workstation",
            "Automation context: possible",
            "Required reporting state: account-level association supported; person-level attribution Unknown",].join(" • ")}
        />

        <SectionCard
          eyebrow="Attribution Ladder"
          title="Do Not Skip from Account to Person"
        >
          <div className="grid gap-5">
            {attributionLadder.map((item, index) => (
              <article
                key={item.level}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <div className="flex items-start gap-4">
                  <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-cyan-400 font-black text-slate-950">
                    {index + 1}
                  </span>
                  <div>
                    <h3 className="text-lg font-black text-white">
                      {item.level}
                    </h3>
                    <p className="mt-2 text-sm leading-7 text-slate-300">
                      {item.example}
                    </p>
                  </div>
                </div>

                <div className="mt-4 rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-yellow-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-yellow-200">
                    Limit
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.limit}</p>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <FakeLogPanel
          title="Fictional Browser and Account Records"
          logs={[
            "13:46 | NOTIFICATION | evidence=BA-04 | account=Account-A | type=role-change | acknowledgement=Unknown",
            "13:50 | RECOVERY | evidence=BA-06 | account=Account-A | workflow=approved-support-recovery | status=complete",
            "14:01 | AUTH | evidence=BA-01 | account=Account-A | result=success | source_health=Healthy",
            "14:01-14:19 | SESSION | evidence=BA-02 | account=Account-A | state=active | physical_user=Unknown",
            "14:03-14:06 | BROWSER | evidence=BA-03 | context=Support-Console+Workflow-Review | intent=Unknown",
            "14:05 | SYNC | evidence=BA-05 | browser_state=reflected | endpoint=D-17+D-22 | origin=Unknown",
            "14:12 | ATTRIBUTION | person-level=Unknown | reasons=shared-device,session-continuity,automation-possible",
          ]}
        />

        <AnalyzeEvidenceCard
          title="Analyze the Account and Browser Evidence"
          question="Which fictional conclusion is strongest?"
          evidence={[
            "Account A authenticated successfully at 14:01.",
            "The session remained active until 14:19.",
            "The browser summary references the Support Console from 14:03 through 14:06.",
            "D-17 is a shared workstation and the evidence does not independently identify the physical user.",
          ]}
          options={[
            "Person A definitely used the Support Console from 14:03 through 14:06.",
            "The supplied evidence associates Account A with an active session and Support Console browser context during the review window; physical-person attribution and continuous manual control remain unresolved.",
            "The session proves harmful intent.",
            "Because the workstation is shared, none of the account evidence is useful.",
          ]}
          bestAnswer={1}
          explanation="The strongest conclusion preserves supported account, session, and browser-context associations without turning them into unsupported physical-person attribution or intent."
        />

        <SectionCard
          eyebrow="Session Lifecycle"
          title="An Active Session Is a State, Not a Person"
        >
          <p className="leading-8">
            Fictional sessions can start, remain active, renew, become idle,
            time out, or end. Each state describes part of the service
            lifecycle. None automatically proves who physically controlled the
            session at every moment.
          </p>

          <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {sessionStates.map((item) => (
              <div
                key={item.state}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="font-black text-cyan-100">{item.state}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-300">
                  {item.meaning}
                </p>
                <div className="mt-4 rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-yellow-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-yellow-200">
                    Does not prove
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.limit}</p>
                </div>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Ambiguity Patterns"
          title="Six Reasons Browser and Account Evidence Can Mislead"
        >
          <div className="grid gap-5 md:grid-cols-2">
            {ambiguityPatterns.map((item) => (
              <article
                key={item.pattern}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="text-lg font-black text-purple-100">
                  {item.pattern}
                </h3>
                <p className="mt-3 text-sm leading-7 text-slate-300">
                  {item.explanation}
                </p>

                <div className="mt-4 rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-red-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-red-200">
                    Interpretation risk
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.risk}</p>
                </div>

                <div className="mt-4 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-emerald-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-200">
                    Professional control
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.control}</p>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <ScenarioDecisionLab
          title="Scenario Decision Lab 1: The Long-Lived Session"
          scenario="A fictional authentication event shows Account A entered Service S at 14:01. The session remained active until 14:19. Browser activity occurred at 14:15, but D-17 is shared and there is no fresh authentication event at 14:15."
          choices={[
            {
              label: "Choice A",
              response:
                "Report that Person A definitely performed the 14:15 browser activity because Account A originally authenticated at 14:01.",
              outcome:
                "This treats session continuity as proof of continuous physical-person control.",
              tone: "risk",
            },
            {
              label: "Choice B",
              response:
                "Report that the 14:15 browser activity occurred within an active Account A session, preserve the shared-device and stale-session possibilities, and keep physical-person attribution Unknown.",
              outcome:
                "This preserves the session relationship without overstating identity.",
              tone: "best",
            },
            {
              label: "Choice C",
              response:
                "Ignore the browser activity because sessions are never useful.",
              outcome:
                "Session evidence is useful context; the issue is attribution, not relevance.",
              tone: "caution",
            },
          ]}
        />

        <SectionCard
          eyebrow="Synchronization"
          title="Browser State on Two Devices Does Not Reveal Which Device Started It"
        >
          <p className="leading-8">
            Fictional browser state can be reflected across approved devices or
            services. A synchronized page reference, tab state, or account
            context may appear on a second device after originating elsewhere.
            Presence in both locations can be useful while origin remains
            unresolved.
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {[
              [
                "Origin",
                "Which fictional endpoint or service first created the state, if known?",
              ],
              [
                "Reflection",
                "Which fictional locations merely received synchronized state?",
              ],
              [
                "Delay",
                "What fictional synchronization delay could explain later appearance?",
              ],
              [
                "Direction",
                "Is the fictional synchronization relationship one-way, two-way, or Unknown?",
              ],
              [
                "Shared-device context",
                "Could either device be used by more than one approved person?",
              ],
              [
                "Reporting",
                "Can the report support presence while preserving origin and person attribution as Unknown?",
              ],
            ].map(([title, detail]) => (
              <div
                key={title}
                className="rounded-2xl border border-purple-400/25 bg-purple-400/10 p-5 text-purple-50"
              >
                <h3 className="font-black text-purple-100">{title}</h3>
                <p className="mt-2 text-sm leading-6">{detail}</p>
              </div>
            ))}
          </div>
        </SectionCard>

        <AnalyzeEvidenceCard
          title="Analyze Synchronized Browser State"
          question="A fictional Support Console browser state appears on D-17 and D-22 within the expected synchronization interval. What is strongest?"
          evidence={[
            "The state appears on both fictional endpoints.",
            "Synchronization is enabled between the approved browser contexts.",
            "The supplied evidence does not identify which endpoint originated the state.",
            "Both endpoints are managed and approved.",
          ]}
          options={[
            "D-17 definitely originated the browser state.",
            "D-22 definitely originated the browser state.",
            "The supplied evidence supports reflected browser state on both endpoints; origin remains unresolved.",
            "Synchronization proves account compromise.",
          ]}
          bestAnswer={2}
          explanation="Synchronization can explain presence in multiple locations without establishing origin."
        />

        <SectionCard
          eyebrow="Notifications"
          title="Generated Does Not Mean Seen"
        >
          <p className="leading-8">
            A fictional notification can show that a service generated a warning,
            approval, account-change notice, or other message. Unless the
            supplied evidence separately supports acknowledgement, the report
            should not claim the recipient saw, read, understood, or accepted
            the message.
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            {[
              [
                "Generated",
                "The fictional service created the notification.",
              ],
              [
                "Delivered",
                "The fictional service represents the notification as delivered to an approved destination.",
              ],
              [
                "Displayed",
                "The fictional interface represents the notification as shown.",
              ],
              [
                "Acknowledged",
                "The fictional record explicitly supports an acknowledgement event.",
              ],
              [
                "Understood",
                "Usually cannot be established from a notification record alone.",
              ],
              [
                "Acted upon",
                "Requires separate evidence of later action and should not be assumed.",
              ],
            ].map(([title, detail]) => (
              <div
                key={title}
                className="rounded-2xl border border-blue-400/25 bg-blue-400/10 p-5 text-blue-50"
              >
                <h3 className="font-black text-blue-100">{title}</h3>
                <p className="mt-2 text-sm leading-6">{detail}</p>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Privacy and Minimization"
          title="Browser Evidence Should Not Become Broad Personal Surveillance"
        >
          <p className="leading-8">
            Browser and account evidence can expose highly personal context if
            scope is weak. The professional control is to define the exact
            fictional question and use only the minimum evidence fields needed
            to answer it. Broad browsing history, private messages, unrelated
            account data, or personal activity should remain outside scope.
          </p>

          <div className="mt-6 grid gap-4 md:grid-cols-2">
            {privacyQuestions.map((item) => (
              <div
                key={item.question}
                className="rounded-2xl border border-yellow-400/25 bg-yellow-400/10 p-5 text-yellow-50"
              >
                <h3 className="font-black text-yellow-100">{item.question}</h3>
                <p className="mt-2 text-sm leading-6">{item.answer}</p>
              </div>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Question-to-Evidence Mapping"
          title="Use Only the Browser and Account Evidence the Question Needs"
        >
          <div className="grid gap-5">
            {questionToEvidence.map((item) => (
              <article
                key={item.question}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="text-lg font-black text-cyan-100">
                  {item.question}
                </h3>

                <div className="mt-4 grid gap-4 md:grid-cols-3">
                  <div className="rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-emerald-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-200">
                      Useful evidence
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.useful}</p>
                  </div>
                  <div className="rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-red-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-red-200">
                      Exclude
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.exclude}</p>
                  </div>
                  <div className="rounded-xl border border-yellow-400/25 bg-yellow-400/10 p-4 text-yellow-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-yellow-200">
                      Conclusion limit
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.limit}</p>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <ScenarioDecisionLab
          title="Scenario Decision Lab 2: The Notification"
          scenario="A fictional role-change notification was generated for Account A at 13:46. A later session begins at 14:01. There is no supplied acknowledgement record showing that any person saw or accepted the notification."
          choices={[
            {
              label: "Choice A",
              response:
                "Report that Person A knew about and accepted the role change before the session.",
              outcome:
                "Notification generation does not establish acknowledgement, understanding, or acceptance.",
              tone: "risk",
            },
            {
              label: "Choice B",
              response:
                "Report that the service generated a role-change notification before the later session, while acknowledgement and person-level awareness remain Unknown.",
              outcome:
                "This uses the timing relationship without inventing recipient awareness.",
              tone: "best",
            },
            {
              label: "Choice C",
              response:
                "Ignore the notification because acknowledgement is missing.",
              outcome:
                "The notification is still relevant as a generated service event; its meaning is simply limited.",
              tone: "caution",
            },
          ]}
        />

        <SectionCard
          eyebrow="Reporting Language"
          title="Write Browser and Account Findings at the Right Evidence Level"
        >
          <div className="grid gap-5">
            {reportingPatterns.map((item, index) => (
              <article
                key={item.weak}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <p className="text-xs font-black uppercase tracking-[0.16em] text-purple-200">
                  Reporting pattern {index + 1}
                </p>

                <div className="mt-4 grid gap-4 md:grid-cols-2">
                  <div className="rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-red-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-red-200">
                      Overstated
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.weak}</p>
                  </div>
                  <div className="rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-emerald-50">
                    <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-200">
                      Bounded
                    </p>
                    <p className="mt-2 text-sm leading-6">{item.stronger}</p>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Common Mistakes"
          title="Where Browser and Account Evidence Reasoning Fails"
        >
          <div className="grid gap-5 md:grid-cols-2">
            {[
              {
                mistake: "Account equals person",
                why:
                  "Shared devices, delegated access, stale sessions, and other contexts can weaken physical-person attribution.",
                correction:
                  "Report the fictional account association and keep person attribution separate.",
              },
              {
                mistake: "Session means continuous presence",
                why:
                  "A session can remain active after the original user leaves.",
                correction:
                  "Treat session continuity as service state, not continuous physical presence.",
              },
              {
                mistake: "Page reference means intent",
                why:
                  "Browser state may reflect automatic navigation, synchronization, preloading, prior state, or other context.",
                correction:
                  "Report the page reference without claiming intent or attention.",
              },
              {
                mistake: "Notification means awareness",
                why:
                  "Generation does not prove delivery, display, acknowledgement, understanding, or action.",
                correction:
                  "Use the exact notification state supported.",
              },
              {
                mistake: "Synchronization means origin",
                why:
                  "Reflected state may appear on another device after originating elsewhere.",
                correction:
                  "Separate presence from origin.",
              },
              {
                mistake: "Recovery means future safety",
                why:
                  "A completed fictional recovery workflow does not validate every later event.",
                correction:
                  "Evaluate later account and session evidence independently.",
              },
              {
                mistake: "More browser history is better",
                why:
                  "Broad fictional browsing evidence can expose unrelated personal activity and weaken purpose limitation.",
                correction:
                  "Use only minimum relevant invented browser context.",
              },
              {
                mistake: "No new login means same person",
                why:
                  "A long-lived fictional session can continue without a fresh authentication event.",
                correction:
                  "Preserve stale-session and shared-device alternatives.",
              },
            ].map((item) => (
              <article
                key={item.mistake}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="text-lg font-black text-red-100">
                  {item.mistake}
                </h3>

                <div className="mt-4 rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-red-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-red-200">
                    Why it fails
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.why}</p>
                </div>

                <div className="mt-4 rounded-xl border border-emerald-400/25 bg-emerald-400/10 p-4 text-emerald-50">
                  <p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-200">
                    Professional correction
                  </p>
                  <p className="mt-2 text-sm leading-6">{item.correction}</p>
                </div>
              </article>
            ))}
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Safe Fictional Lab"
          title="Build a Browser and Account Activity Reasoning Matrix"
        >
          <p className="leading-8">
            Use only BA-01 through BA-06 and the invented browser and account
            records supplied on this page. Do not access, inspect, search,
            query, collect, export, recover, monitor, or review any real
            browser, account, browsing history, private communication,
            credential, session, recovery record, notification, device, or
            service.
          </p>

          <div className="mt-6 grid gap-5">
            {[
              {
                phase: "Phase 1 — Define bounded questions",
                tasks: [
                  "Write one fictional question for authentication, one for session continuity, one for browser context, and one for notification state.",
                  "State the decision owner for each question.",
                  "List at least three browser/account questions that remain explicitly out of scope.",
                ],
              },
              {
                phase: "Phase 2 — Map evidence categories",
                tasks: [
                  "Map each question to the minimum useful fictional evidence category.",
                  "Add source health, time type, shared-device context, privacy, and attribution-limit fields.",
                  "List unrelated evidence that must remain excluded.",
                ],
              },
              {
                phase: "Phase 3 — Analyze session and attribution",
                tasks: [
                  "Use BA-01 and BA-02 to write an account-level session finding.",
                  "Explain why session continuity does not prove continuous physical presence.",
                  "Write one person-level attribution statement that must remain Unknown.",
                ],
              },
              {
                phase: "Phase 4 — Analyze browser and synchronization state",
                tasks: [
                  "Use BA-03 and BA-05 to write one browser-context finding and one reflected-state finding.",
                  "State what the evidence does not prove about intent or origin.",
                  "Add one automation alternative and one synchronization alternative.",
                ],
              },
              {
                phase: "Phase 5 — Analyze notifications and recovery context",
                tasks: [
                  "Use BA-04 to distinguish generated, delivered, displayed, acknowledged, understood, and acted-upon states.",
                  "Use BA-06 only as recovery context rather than proof of future authorization.",
                  "Write one non-proof statement for each.",
                ],
              },
              {
                phase: "Phase 6 — Report",
                tasks: [
                  "Create one High-confidence finding, two Conditional findings, and one Unknown person-attribution finding.",
                  "Write at least six non-proof statements.",
                  "Create a public-safe leadership summary using only invented account and browser evidence.",
                ],
              },
            ].map((item) => (
              <article
                key={item.phase}
                className="rounded-2xl border border-slate-700 bg-slate-950 p-5"
              >
                <h3 className="text-lg font-black text-cyan-100">
                  {item.phase}
                </h3>
                <ul className="mt-4 space-y-3 text-sm leading-7 text-slate-300">
                  {item.tasks.map((task) => (
                    <li key={task}>• {task}</li>
                  ))}
                </ul>
              </article>
            ))}
          </div>

          <div className="mt-6 rounded-2xl border border-yellow-400/30 bg-yellow-400/10 p-5 text-yellow-50">
            <p className="font-black">Lab boundary</p>
            <p className="mt-2 leading-7">
              This activity is a reasoning and documentation exercise using
              invented, pre-supplied evidence only. It does not authorize real
              browser inspection, account access, password or credential use,
              recovery-secret access, private-message review, browsing-history
              collection, session takeover, monitoring, surveillance, device
              access, extraction, or technical investigation.
            </p>
          </div>
        </SectionCard>

        <SectionCard
          eyebrow="Advanced Challenge"
          title="Explain Why the Account Answer Can Be Stronger Than the Person Answer"
        >
          <p className="leading-8">
            A fictional executive asks, “Did Person A use the Support Console?”
            The evidence strongly supports that Account A authenticated, the
            session remained active, and the browser context referenced the
            Support Console. D-17 is shared and no supplied evidence identifies
            the physical user at the moment of the browser event.
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            {[
              "Write the strongest account-level finding.",
              "Write the strongest session-level finding.",
              "Write the strongest browser-context finding.",
              "Explain why the person-level answer remains Unknown.",
              "Show how shared-device and stale-session alternatives weaken person attribution without weakening account association.",
              "Explain why preserving Unknown is more professional than choosing a person based on convenience.",
              "Identify one fictional business or security decision that can still be made from the account-level evidence.",
              "Create a public-safe summary that demonstrates strong evidence reasoning without exposing private browser activity.",
            ].map((item) => (
              <div
                key={item}
                className="rounded-2xl border border-purple-400/25 bg-purple-400/10 p-5 text-sm leading-7 text-purple-50"
              >
                {item}
              </div>
            ))}
          </div>
        </SectionCard>

        <DefenderChecklist
          title="A8.6 Browser and Account Activity Checklist"
          items={[
            "I can distinguish fictional authentication, session, browser, notification, synchronization, account-state, shared-device, and recovery-context evidence.",
            "I can explain why a successful authentication event supports an account-level conclusion rather than automatic person-level attribution.",
            "I can explain why an active session does not prove continuous physical presence or manual activity.",
            "I can explain why browser page references do not automatically prove intent, attention, or causation.",
            "I can distinguish notification generation from delivery, display, acknowledgement, understanding, and action.",
            "I can separate synchronized browser presence from origin.",
            "I can preserve shared-device, stale-session, automation, and synchronization alternatives.",
            "I can use recovery context without treating later account activity as automatically authorized.",
            "I can map bounded questions to minimum-necessary browser and account evidence.",
            "I can exclude unrelated private communications, broad browsing history, credentials, recovery secrets, and personal activity.",
            "I can write bounded browser/account findings with explicit non-proof statements and Unknown attribution.",
            "I can keep every example fully fictional, pre-supplied, defensive, non-invasive, privacy-safe, and public-safe.",
          ]}
        />

        <MiniQuiz
          title="A8.6 Mini Quiz: Browser and Account Activity Concepts"
          questions={[
            {
              question:
                "A fictional authentication record shows Account A successfully entered a service session. What does that alone prove?",
              choices: [
                "Person A physically performed the authentication.",
                "Account A was represented as successfully authenticated, subject to source and context limits.",
                "The account was compromised.",
                "Every later action in the session was manual.",
              ],
              answer: 1,
              explanation:
                "Authentication evidence supports account-level state, not automatic physical-person attribution or later manual control.",
            },
            {
              question:
                "A fictional session remains active for eighteen minutes on a shared workstation. What is strongest?",
              choices: [
                "The original person remained at the device for eighteen minutes.",
                "The account session remained represented as active; continuous physical-person control is not independently established.",
                "Every event in the session was authorized.",
                "The session proves harmful intent.",
              ],
              answer: 1,
              explanation:
                "Session continuity is service state, not proof of continuous person presence.",
            },
            {
              question:
                "A fictional browser summary references the Support Console. What does that alone prove?",
              choices: [
                "The user intentionally opened and read the page.",
                "The browser context represented the Support Console during the review window, subject to source and automation limits.",
                "The page caused the incident.",
                "The account was compromised.",
              ],
              answer: 1,
              explanation:
                "Browser context is not the same as intent, attention, causation, or physical-user attribution.",
            },
            {
              question:
                "A fictional notification was generated for Account A, but no acknowledgement record exists. What is strongest?",
              choices: [
                "The user saw and accepted the notification.",
                "The service generated the notification; acknowledgement and awareness remain Unknown.",
                "The notification can be ignored.",
                "The notification proves authorization.",
              ],
              answer: 1,
              explanation:
                "Generation does not prove display, acknowledgement, understanding, or action.",
            },
            {
              question:
                "A fictional browser state appears on two synchronized endpoints. What is strongest?",
              choices: [
                "The first endpoint listed definitely originated the state.",
                "The second endpoint definitely originated the state.",
                "The evidence supports reflected presence on both endpoints while origin may remain unresolved.",
                "Synchronization proves compromise.",
              ],
              answer: 2,
              explanation:
                "Synchronization can reflect state across devices without proving origin.",
            },
            {
              question:
                "A fictional account completed an approved recovery workflow before later activity. What does that establish?",
              choices: [
                "Every later action was authorized.",
                "The account was permanently safe.",
                "Only that the account completed the approved recovery workflow; later activity still requires independent evaluation.",
                "The recovery workflow caused the later session.",
              ],
              answer: 2,
              explanation:
                "Recovery context is useful but does not validate every future event.",
            },
            {
              question:
                "Why should a fictional investigation avoid broad browsing history when the question only concerns one service page?",
              choices: [
                "Because browser evidence is never useful.",
                "Because purpose limitation and privacy require the minimum evidence necessary for the approved question.",
                "Because broad history always contains false data.",
                "Because only notifications are allowed.",
              ],
              answer: 1,
              explanation:
                "Minimum-necessary evidence protects privacy and improves forensic relevance.",
            },
          ]}
        />

        <PortfolioPrompt
          title="Portfolio Prompt: Browser and Account Activity Reasoning Package"
          prompt="Create a fully fictional A8.6 Browser and Account Activity Reasoning Package for Northbridge. Include at least eight invented evidence items across authentication, session state, browser context, notifications, account state changes, synchronization, shared-device context, and recovery/support context. For each item include evidence ID, bounded question, evidence category, account or session object, source owner, source health, event time, session state, device context, synchronization state, automation possibility, privacy limit, observation, what it supports, what it does not prove, person-attribution limit, confidence, next owner question, and reporting language. Include one shared-device case, one stale-session case, one automation case, one synchronized-browser-state case, one notification-without-acknowledgement case, one recovery-context case, one rejected person-level attribution, one rejected intent claim, at least six non-proof statements, a leadership summary, and a public-safe portfolio summary. Every organization, person, account, device, browser context, service, session, notification, event, timestamp, owner, finding, and outcome must be invented."
          tips={[
            "Keep account, session, device, browser, notification, and person-level conclusions separate.",
            "Use shared-device, stale-session, automation, and synchronization alternatives before person attribution.",
            "Treat notification generation as different from acknowledgement or awareness.",
            "Use recovery state only as context; evaluate later events independently.",
            "Exclude unrelated browsing history, private messages, credentials, secrets, and personal activity.",
            "Keep the portfolio artifact fully fictional, non-invasive, defensive, privacy-safe, and public-safe.",
          ]}
        />

        <SectionCard
          eyebrow="Confidence / Readiness Reflection"
          title="Are You Ready for A8.7 Log Correlation for Forensics?"
        >
          <p className="leading-8">
            Rate your readiness from 1 to 5 for authentication evidence, session
            lifecycle, browser context, notifications, synchronization,
            shared-device ambiguity, stale sessions, automation, recovery
            context, privacy, person-attribution limits, and bounded reporting.
          </p>

          <div className="mt-5 grid gap-4 md:grid-cols-2">
            {[
              "I can explain what a fictional authentication event supports without identifying the physical person.",
              "I can explain why session continuity does not prove continuous physical presence.",
              "I can describe browser context without claiming intent or attention.",
              "I can distinguish notification generation from acknowledgement and awareness.",
              "I can separate synchronized browser presence from origin.",
              "I can preserve shared-device, stale-session, and automation alternatives.",
              "I can use recovery context without treating later actions as automatically authorized.",
              "I can map a bounded question to minimum-necessary browser/account evidence.",
              "I can keep unrelated private activity, credentials, and communications outside scope.",
              "I can write person-attribution Unknowns clearly and professionally.",
            ].map((item) => (
              <div
                key={item}
                className="rounded-2xl border border-cyan-400/25 bg-cyan-400/10 p-5 text-sm leading-7 text-cyan-50"
              >
                {item}
              </div>
            ))}
          </div>
        </SectionCard>

        <KeyTakeaways
          takeaways={[
            "Authentication evidence supports fictional account-level state, not automatic physical-person attribution.",
            "Session continuity describes service state and does not prove continuous presence or manual control.",
            "Browser context can show that a fictional page or application was represented without proving intent, attention, or causation.",
            "Notification generation is different from delivery, display, acknowledgement, understanding, and action.",
            "Shared devices, stale sessions, automation, and synchronization can significantly weaken person-level attribution.",
            "Synchronized browser or account state supports reflected presence without automatically establishing origin.",
            "Account recovery context does not guarantee that later activity was authorized or safe.",
            "Question-driven minimization protects privacy by excluding broad browsing history, private messages, credentials, secrets, and unrelated personal activity.",
            "Professional reports keep account, session, device, browser, notification, person attribution, intent, and causation as separate evidence levels.",
            "CyberShield browser and account evidence remains fully fictional, pre-supplied, non-invasive, defensive, privacy-safe, and public-safe.",
          ]}
        />

        <section className="rounded-2xl border border-yellow-400/30 bg-yellow-400/10 p-6 text-yellow-50">
          <p className="text-xs font-black uppercase tracking-[0.18em] text-yellow-200">
            Safety Boundary
          </p>
          <h2 className="mt-2 text-2xl font-black">
            This Lesson Teaches Browser and Account Evidence Reasoning, Not Account Access
          </h2>
          <p className="mt-3 leading-7">
            Nothing in A8.6 authorizes access, investigation, monitoring,
            browsing-history inspection, account access, credential use,
            password recovery, secret recovery, security-question review,
            backup-code access, private-message review, session takeover,
            collection, extraction, imaging, synchronization manipulation,
            configuration changes, surveillance, or examination involving any
            real browser, account, device, session, service, application,
            organization, incident, classmate, teacher, family member, or other
            person. Use only fully invented, pre-supplied evidence descriptions.
          </p>
        </section>

        <section className="rounded-2xl border border-emerald-400/30 bg-emerald-400/10 p-6 text-emerald-50">
          <p className="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-200">
            Lesson Complete
          </p>
          <h2 className="mt-2 text-2xl font-black">
            Continue to Log Correlation for Forensics
          </h2>
          <p className="mt-3 max-w-3xl leading-7">
            A8.6 established how to reason about fictional authentication,
            sessions, browser context, notifications, shared-device ambiguity,
            synchronization, and account state without over-attributing a
            person. A8.7 connects multiple supplied evidence sources and asks
            how to correlate identity, endpoint, application, service, supplier,
            and audit records while preserving provenance, time, source health,
            contradictions, and uncertainty.
          </p>

          <div className="mt-6">
            <Navigation />
          </div>
        </section>
      </div>

      <Footer />
    </main>
  );
}